import type { Receta, ConfiguracionHorno, NotaGeneral } from './types'

// Store de recetas - aquí irás agregando las recetas
export const recetas: Receta[] = [
  {
    id: "1",
    nombre: "Vinagreta de Limón",
    categoria: "Salsas",
    ingredientes: [
      // Grupo A - Base ácida
      { nombre: "Jugo de limón", cantidad: 200, unidad: "ml", grupo: "Base ácida" },
      { nombre: "Vinagre de alcohol", cantidad: 100, unidad: "ml", grupo: "Base ácida" },
      // Grupo B - Aceites
      { nombre: "Aceite de girasol", cantidad: 250, unidad: "ml", grupo: "Aceites" },
      { nombre: "Aceite de oliva", cantidad: 250, unidad: "ml", grupo: "Aceites" },
    ],
    instrucciones: [
      "Colocar los ingredientes del Grupo A (jugo de limón y vinagre) en una licuadora",
      "Encender la licuadora e incorporar el Grupo B (aceites) en forma de hilo hasta lograr una emulsión estable"
    ],
    notas: "Emulsión estándar",
    rendimiento: "800 ml aprox."
  },
  {
    id: "2",
    nombre: "Mermelada de Cebolla",
    categoria: "Salsas",
    ingredientes: [
      // Grupo A
      { nombre: "Cebolla blanca", cantidad: 1000, unidad: "g", grupo: "Grupo A" },
      { nombre: "Azúcar", cantidad: 400, unidad: "g", grupo: "Grupo A" },
      // Grupo B - Líquidos y Condimentos
      { nombre: "Jerez", cantidad: 150, unidad: "ml", grupo: "Líquidos y Condimentos" },
      { nombre: "Vinagre de alcohol", cantidad: 20, unidad: "ml", grupo: "Líquidos y Condimentos" },
      { nombre: "Sal fina", cantidad: 8, unidad: "g", grupo: "Líquidos y Condimentos" },
      { nombre: "Pimienta molida", cantidad: 0, unidad: "a gusto", grupo: "Líquidos y Condimentos" },
    ],
    instrucciones: [
      "Cortar la cebolla en juliana con mandolina para asegurar uniformidad",
      "En una olla a fuego medio-alto, colocar la cebolla, el azúcar, el jerez, el vinagre, la sal y la pimienta",
      "Cocinar revolviendo periódicamente",
      "Una vez que el líquido se evapore por completo, procesar hasta obtener la textura de mermelada"
    ],
    notas: "La proporción de azúcar es del 40% sobre el peso de la cebolla limpia"
  },
  {
    id: "3",
    nombre: "Masa de Arepas",
    categoria: "Masas",
    ingredientes: [
      // Grupo A
      { nombre: "Agua", cantidad: 1400, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Sal fina", cantidad: 45, unidad: "g", grupo: "Grupo A" },
      // Grupo B
      { nombre: "Harina de maíz", cantidad: 1000, unidad: "g", grupo: "Grupo B" },
      // Grupo C
      { nombre: "Manteca pomada", cantidad: 240, unidad: "g", grupo: "Grupo C" },
      { nombre: "Queso reggianito rallado", cantidad: 270, unidad: "g", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Disolver la sal en el agua",
      "Agregar la harina de maíz, integrar y dejar hidratar por 10 minutos",
      "Incorporar la manteca pomada y el queso. Amasar enérgicamente hasta que no queden grumos",
      "Porcionar en bollos de 80 g, dar forma y cocinar en plancha (Darto)"
    ],
    notas: "1 paquete estándar de harina de maíz = 1 kg",
    rendimiento: "~3.4 kg de masa (aprox. 42-43 unidades de 80 g)"
  },
  {
    id: "4",
    nombre: "Mezcla de Cachapas",
    categoria: "Masas",
    ingredientes: [
      // Grupo A
      { nombre: "Choclo desgranado (peso neto)", cantidad: 600, unidad: "g", grupo: "Grupo A" },
      // Grupo B - Secos
      { nombre: "Azúcar", cantidad: 120, unidad: "g", grupo: "Secos" },
      { nombre: "Harina de maíz", cantidad: 125, unidad: "g", grupo: "Secos" },
      { nombre: "Fécula de mandioca", cantidad: 50, unidad: "g", grupo: "Secos" },
      { nombre: "Ají molido", cantidad: 5, unidad: "g", grupo: "Secos" },
      { nombre: "Sal fina", cantidad: 10, unidad: "g", grupo: "Secos" },
      // Grupo C - Líquidos
      { nombre: "Huevo", cantidad: 2, unidad: "un", grupo: "Líquidos" },
    ],
    instrucciones: [
      "Desgranar el choclo y limpiar los restos de pelos",
      "Mezclar el choclo con todos los ingredientes del Grupo B (secos)",
      "Procesar en dos tandas: una tanda procesada apenas (para mantener textura de grano) y la otra tanda procesada a fondo",
      "Unificar ambas tandas en un bowl y agregar los huevos",
      "Cocinar en sartén con aceite y manteca usando aro de 12 cm. Medida: 1 bochero y medio (bochero azul). Cocción de un solo lado"
    ],
    rendimiento: "~1.2 kg de mezcla (aprox. 14-15 porciones de 80 g)"
  },
  {
    id: "5",
    nombre: "Salsa Tahini Ahumado",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Tahini ahumado", cantidad: 250, unidad: "g" },
      { nombre: "Ajo (rallado fino con Microplane)", cantidad: 10, unidad: "g" },
      { nombre: "Sal fina", cantidad: 10, unidad: "g" },
      { nombre: "Agua fría filtrada", cantidad: 80, unidad: "ml" },
      { nombre: "Jugo de limón", cantidad: 75, unidad: "ml" },
    ],
    instrucciones: [
      "En un bowl, colocar el tahini, la sal y el ajo rallado",
      "Incorporar el agua fría y el jugo de limón",
      "Batir enérgicamente con batidor de alambre hasta que la salsa cambie de color, quede lisa y espese",
      "Probar y rectificar el equilibrio entre sal y acidez"
    ],
    notas: "Textura final: lisa y emulsionada"
  },
  {
    id: "6",
    nombre: "Puré de Coliflor Caramelizado",
    categoria: "Purés",
    ingredientes: [
      { nombre: "Chocolate blanco Callebaut", cantidad: 1000, unidad: "g", grupo: "Chocolate Blanco Caramelizado" },
      { nombre: "Coliflor entero", cantidad: 1000, unidad: "g", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 40, unidad: "cc", grupo: "Grupo A" },
      { nombre: "Sal fina", cantidad: 10, unidad: "g", grupo: "Grupo A" },
      { nombre: "Ajo écrasé", cantidad: 5, unidad: "u", grupo: "Grupo A" },
      { nombre: "Manteca", cantidad: 120, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 100, unidad: "ml", grupo: "Grupo C" },
      { nombre: "Chocolate blanco caramelizado (picado)", cantidad: 100, unidad: "g", grupo: "Grupo C" },
      { nombre: "Manteca fría en cubos", cantidad: 80, unidad: "g", grupo: "Grupo C" },
    ],
    instrucciones: [
      "CHOCOLATE BLANCO CARAMELIZADO: Prender horno a 120°C. En una placa con silpat, volcar el chocolate blanco. Llevar al horno y remover el chocolate cada 5 minutos para que se caramelice de manera uniforme. Una vez dorado, volcar en moldes de silicona y dejar enfriar de un día para otro.",
      "Picar el coliflor. En una olla ancha y baja poner el Grupo A junto con una cucharada de manteca (Grupo B).",
      "Cocinar/confitar a fuego bajo agregando más manteca de a poco a cucharadas. Si es necesario, agregar un poco de agua para despegar o evitar que se queme. El coliflor debe quedar bien caramelizado.",
      "Separar los sólidos de los líquidos. Licuar los sólidos agregando los líquidos más el agua del Grupo C en hilo para emulsionar.",
      "Terminar montando con el chocolate blanco caramelizado picado y la manteca fría en cubos del Grupo C.",
    ],
    notas: "El Grupo A rinde por 3. Si el coliflor está frío al licuar, el chocolate debe estar derretido y la manteca no necesariamente fría. El agua del Grupo C puede ajustarse entre 50 y 150 ml según la textura deseada.",
  },
  {
    id: "8",
    nombre: "Pickles de Jalapeño",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Jalapeño en juliana", cantidad: 500, unidad: "g", grupo: "Grupo A" },
      { nombre: "Vinagre de alcohol", cantidad: 800, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 300, unidad: "g", grupo: "Grupo B" },
      { nombre: "Azúcar", cantidad: 250, unidad: "g", grupo: "Grupo C" },
      { nombre: "Sal", cantidad: 50, unidad: "g", grupo: "Grupo C" },
      { nombre: "Hojas de orégano", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Blanquear el jalapeño (Grupo A) en agua hirviendo durante 2 minutos.",
      "Cocinar 10 minutos en el Grupo B junto con el Grupo C.",
    ],
  },
  {
    id: "9",
    nombre: "Pickles de Cebolla",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Cebolla morada en pluma", cantidad: 1000, unidad: "g", grupo: "Grupo A" },
      { nombre: "Vinagre", cantidad: 900, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 300, unidad: "g", grupo: "Grupo B" },
      { nombre: "Azúcar", cantidad: 350, unidad: "g", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 100, unidad: "g", grupo: "Grupo B" },
      { nombre: "Semillas de mostaza", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
      { nombre: "Hojas de laurel", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
      { nombre: "Semillas de pimienta", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
      { nombre: "Eneldo", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Infusionar el Grupo B junto con el Grupo C hasta hervir.",
      "Agregar el Grupo A (cebolla morada) una vez que esté hirviendo. Cocinar 8 minutos.",
    ],
  },
  {
    id: "7",
    nombre: "Puré de Flores de Coliflor",
    categoria: "Purés",
    ingredientes: [
      { nombre: "Coliflor (flores)", cantidad: 1000, unidad: "g", grupo: "Grupo A" },
      { nombre: "Leche", cantidad: 550, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Agua", cantidad: 550, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Ajo aplastado", cantidad: 3, unidad: "u", grupo: "Grupo A" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Pimienta blanca", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Nuez moscada", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Manteca en cubos congelados", cantidad: 0, unidad: "a gusto", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Cocinar las flores de coliflor partiendo desde frío en iguales cantidades de agua y leche, con los ajos aplastados, sal, pimienta blanca y nuez moscada.",
      "Llevar a hervor, bajar el fuego y retirar cuando estén cocidos pero aún al dente.",
      "Enfriar y reservar. El líquido de cocción se puede reciclar hasta dos veces.",
      "Procesar el Grupo A en licuadora y agregar el Grupo B (manteca en cubos congelados) para que emulsione. Rectificar la sal y guardar.",
    ],
    rendimiento: "900 g aprox.",
    notas: "El líquido de cocción puede reutilizarse hasta dos veces.",
  },
  {
    id: "10",
    nombre: "Pil Pil de Pescado",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Gelatina de colágeno", cantidad: 100, unidad: "g", grupo: "Base" },
      { nombre: "Manteca derretida", cantidad: 300, unidad: "g", grupo: "Grasas" },
      { nombre: "Beurre noisette", cantidad: 100, unidad: "g", grupo: "Grasas" },
      { nombre: "Chardonnay reducido", cantidad: 30, unidad: "ml", grupo: "Terminación" },
    ],
    instrucciones: [
      "Procesar la gelatina en Thermomix a 40°C, velocidad 4.5 durante 5 minutos hasta que emulsione y tome cuerpo.",
      "Agregar el Chardonnay reducido en cuanto la gelatina ligue.",
      "Sin interrumpir, incorporar ambas mantecas mezcladas en hilo fino por el bocal (~2 min) hasta obtener una emulsión homogénea y brillante.",
      "Mantener a 35–40°C para el servicio.",
    ],
    notas: "No usar velocidad alta ni trabajar la gelatina semigelificada: rompe la emulsión. Servir siempre en caliente.",
    rendimiento: "~530 ml",
  },
  {
    id: "11",
    nombre: "Puré de Calabaza Noisette",
    categoria: "Purés",
    ingredientes: [
      { nombre: "Zapallo anco", cantidad: 2, unidad: "u", grupo: "Grupo A" },
      { nombre: "Ajo", cantidad: 20, unidad: "g", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 50, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Sal fina", cantidad: 10, unidad: "g", grupo: "Grupo B" },
      { nombre: "Pimienta molida", cantidad: 5, unidad: "g", grupo: "Grupo B" },
      { nombre: "Manteca noisette", cantidad: 300, unidad: "g", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Lavar, pelar y retirar semillas de la calabaza.",
      "Precalentar el horno a 180 °C.",
      "Disponer en una placa con el Grupo B y tapar muy bien con papel aluminio.",
      "Llevar al horno por 30 minutos, hasta que la calabaza esté cocida.",
      "Retirar el aluminio de la placa, subir a 190 grados y dejar que se caramelice un poco.",
      "Una vez caramelizada, retirar el ajo y procesar en Thermomix con la manteca noisette hasta lograr una textura bien lisa y sedosa. Si no está caliente, darle temperatura en la Thermomix.",
    ],
    notas: "2 unidades de zapallo anco ≈ 2.5 kg.",
  },
  {
    id: "12",
    nombre: "Gelatina de Pescado",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Espinazo, cabeza y pieles de pesca blanca (alta en colágeno)", cantidad: 2, unidad: "kg" },
    ],
    instrucciones: [
      "Limpiar bien todo en agua con hielo para sacar impurezas y sangre.",
      "Una vez limpios, llevar a una olla, cubrir con agua fría nueva y llevar a hervor fuerte limpiando y espumando todas las impurezas que floten en la superficie.",
      "Cocinar fuerte hasta que haya reducido a la mitad y los huesos empiecen a desarmarse, el líquido haya tomado un color blancuzco-amarillento y el caldo esté más espeso. En ese punto, colar primero en un chino fino y después por una tela de queso.",
      "Transferir el líquido a un cambro y dejar enfriar. Va a quedar duro como una gelatina.",
    ],
    notas: "Base de la emulsión del Pil Pil de Pescado.",
  },
  {
    id: "13",
    nombre: "Puré de Cajú",
    categoria: "Purés",
    ingredientes: [
      { nombre: "Castañas de cajú", cantidad: 1, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Agua fría", cantidad: 300, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 175, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Diente de ajo sin germen", cantidad: 1, unidad: "u", grupo: "Grupo B" },
      { nombre: "Sal fina", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Remojar las castañas de cajú en agua por lo menos 12 horas para activarlas.",
      "Una vez pasado ese tiempo escurrir el agua y poner las castañas en un vaso de licuadora.",
      "Agregar el vinagre de alcohol y el agua bien fría. Procesar a velocidad máxima 2 o 3 minutos.",
      "Agregar el diente de ajo y procesar hasta lograr una textura bien lisa. No debe tener grumos; si los tiene, agregar más agua fría y seguir procesando.",
      "Salar a gusto y rectificar de ajo y/o de vinagre si hace falta.",
    ],
    rendimiento: "2,095 kg",
  },
  {
    id: "14",
    nombre: "Pesto de Pasas y Nueces",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Nueces pecan tostadas", cantidad: 375, unidad: "g" },
      { nombre: "Pasas de uva hidratadas", cantidad: 125, unidad: "g" },
      { nombre: "Perejil plano", cantidad: 0.25, unidad: "atado" },
      { nombre: "Ajo (diente pequeño, rallado)", cantidad: 1, unidad: "u" },
      { nombre: "Ralladura de limón", cantidad: 3, unidad: "u" },
      { nombre: "Vinagre blanco de alcohol", cantidad: 45, unidad: "ml" },
      { nombre: "Aceto Millán (reducción)", cantidad: 40, unidad: "ml" },
      { nombre: "Aceite de oliva", cantidad: 60, unidad: "ml" },
      { nombre: "Aceite de girasol", cantidad: 70, unidad: "ml" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n" },
    ],
    instrucciones: [
      "Si no tenés pasas de uva hidratadas: hidratar las pasas de uva y separar 125 g de las ya hidratadas.",
      "Picar las nueces pecán, las pasas y el perejil. Condimentar todo.",
    ],
  },
  {
    id: "15",
    nombre: "Pickle de Shiitake",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Shiitake fresco cortado en juliana", cantidad: 1, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Miel", cantidad: 500, unidad: "g", grupo: "Grupo B" },
      { nombre: "Salsa de soja", cantidad: 500, unidad: "g", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 500, unidad: "g", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Llevar el Grupo B a hervor en una olla, apagar y verter sobre los shiitakes frescos.",
    ],
  },
  {
    id: "16",
    nombre: "Reducción de Oporto",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Vino tinto", cantidad: 200, unidad: "ml" },
      { nombre: "Oporto", cantidad: 200, unidad: "ml" },
      { nombre: "Azúcar", cantidad: 200, unidad: "g" },
    ],
    instrucciones: [
      "Poner en una olla y reducir hasta punto de jalea.",
    ],
  },
  {
    id: "17",
    nombre: "Provenzal de Limón de Anafe",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Perejil", cantidad: 0.5, unidad: "atado", grupo: "Grupo A" },
      { nombre: "Ajo", cantidad: 8, unidad: "g", grupo: "Grupo A" },
      { nombre: "Ralladura de limón", cantidad: 4, unidad: "u", grupo: "Grupo A" },
      { nombre: "Aceite de oliva", cantidad: 70, unidad: "g", grupo: "Grupo B" },
      { nombre: "Aceite de girasol", cantidad: 30, unidad: "g", grupo: "Grupo B" },
      { nombre: "Jugo de limón", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 0, unidad: "pizca", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Deshojar y lavar las hojas de perejil. Picar bien. Tiene que llenar más o menos ½ cambro de 1/9.",
      "Agregar el ajo rallado con microplane y la ralladura de 4 limones, también hecha con microplane.",
      "Condimentar con los aceites, sal, vinagre y jugo de limón hasta que esté rica.",
    ],
    notas: "El paso 3 menciona vinagre para condimentar, aunque no figura en el mise en place.",
  },
  {
    id: "18",
    nombre: "Ricota de Anafe",
    categoria: "Elaboraciones",
    ingredientes: [
      { nombre: "Leche entera", cantidad: 20, unidad: "l", grupo: "Grupo A" },
      { nombre: "Crema de leche de sachet", cantidad: 2.5, unidad: "l", grupo: "Grupo A" },
      { nombre: "Vinagre blanco de alcohol", cantidad: 1, unidad: "l", grupo: "Grupo A" },
      { nombre: "Crema de leche de sachet", cantidad: 1.6, unidad: "l", grupo: "Grupo B" },
      { nombre: "Sal fina marina", cantidad: 30, unidad: "g", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Colocar la leche entera y la crema de leche de sachet en una olla grande y llevar a fuego medio hasta 95 grados.",
      "Agregar el vinagre de alcohol y apagar el fuego. Tapar y reposar 10 minutos para que se formen los grumos (curds).",
      "Filtrar la ricota con una araña sobre un chino con tela de queso. Dejar filtrando en frío por lo menos 12 horas.",
      "Una vez pasado ese tiempo colocar la ricota en un bowl y agregar la crema de leche de sachet del Grupo B y la sal. Probar y rectificar si hace falta.",
      "Reservar en cambro para el servicio.",
    ],
    rendimiento: "5 kg",
    notas: "La ficha trae cantidades reducidas entre paréntesis: 2 l de leche, 250 ml de crema, 65 ml de vinagre, 160 ml de crema (Grupo B), 5 g de sal.",
  },
  {
    id: "19",
    nombre: "Repollo Braseado",
    categoria: "Guarniciones",
    ingredientes: [
      { nombre: "Repollos blancos", cantidad: 3, unidad: "u" },
      { nombre: "Aceite de oliva", cantidad: 0, unidad: "c/n" },
      { nombre: "Ajo picado", cantidad: 6, unidad: "dientes" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n" },
      { nombre: "Pimienta", cantidad: 0, unidad: "a gusto" },
      { nombre: "Agua", cantidad: 1, unidad: "taza" },
    ],
    instrucciones: [
      "Cortar los repollos en cuartos, manteniendo el corazón. Acomodarlos en la placa y condimentar con aceite de oliva, ajo picado, sal, pimienta y 1 taza de agua.",
      "Cubrir con papel aluminio y hornear a 160 °C hasta que estén blandos. Darlos vuelta a mitad de cocción y controlar que nunca se queden sin líquido.",
    ],
    rendimiento: "12 porciones",
  },
  {
    id: "20",
    nombre: "Salsa de Levadura 2.0",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Manteca", cantidad: 450, unidad: "g", grupo: "Manteca de levadura y cerveza" },
      { nombre: "Levadura nutricional", cantidad: 100, unidad: "g", grupo: "Manteca de levadura y cerveza" },
      { nombre: "Cerveza rubia o de trigo", cantidad: 225, unidad: "ml", grupo: "Manteca de levadura y cerveza" },
      { nombre: "Cerveza rubia o de trigo", cantidad: 0, unidad: "c/n", grupo: "Salsa (en servicio, por repollo)" },
      { nombre: "Manteca de levadura y cerveza", cantidad: 0, unidad: "c/n", grupo: "Salsa (en servicio, por repollo)" },
      { nombre: "Jugo de limón", cantidad: 0, unidad: "c/n", grupo: "Salsa (en servicio, por repollo)" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Salsa (en servicio, por repollo)" },
    ],
    instrucciones: [
      "Hacer manteca noisette. Apagar el fuego y dejar asentar 5 min.",
      "Agregar la levadura nutricional cuando la manteca aún está caliente, para que se tueste. Enfriar completamente.",
      "Una vez que la manteca esté completamente fría, reducir la cerveza a la mitad.",
      "Llevar la reducción de cerveza caliente a la Thermomix y procesar mientras le agregás la manteca con levadura fría para generar una emulsión.",
      "En servicio (por cada repollo): poner en una sartén 2 cucharadas de cerveza (usar cucharada medidora) y emulsionar con la manteca de levadura y cerveza. Condimentar con jugo de limón y sal.",
    ],
    notas: "Proporción de referencia: 113 ml de reducción de cerveza por 550 g de manteca de levadura tostada.",
  },
  {
    id: "21",
    nombre: "Ali Oli Tonatto",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Pescado confitado en recortes", cantidad: 300, unidad: "g", grupo: "Grupo A" },
      { nombre: "Anchoas", cantidad: 4, unidad: "u", grupo: "Grupo A" },
      { nombre: "Alcaparras lavadas", cantidad: 50, unidad: "g", grupo: "Grupo A" },
      { nombre: "Caldo de pollo", cantidad: 100, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Yemas", cantidad: 4, unidad: "u", grupo: "Grupo A" },
      { nombre: "Mostaza de Dijon", cantidad: 1, unidad: "cda", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 800, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 200, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Jugo de limón", cantidad: 0.5, unidad: "u", grupo: "Grupo C" },
      { nombre: "Vinagre blanco", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Pimienta blanca", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Hacer una pasta con el Grupo A lo más lisa posible.",
      "Emulsionar con el Grupo B.",
      "Condimentar con el Grupo C.",
    ],
    notas: "El pescado va confitado y levemente ahumado, sin que se seque. Anchoas: Herman Viva.",
  },
  {
    id: "22",
    nombre: "Arroz Marcado",
    categoria: "Guarniciones",
    ingredientes: [
      { nombre: "Arroz", cantidad: 200, unidad: "g", grupo: "Por porción" },
      { nombre: "Sofrito", cantidad: 150, unidad: "g", grupo: "Por porción" },
      { nombre: "Fondo de pescado", cantidad: 230, unidad: "g", grupo: "Por porción" },
      { nombre: "Demi glace", cantidad: 50, unidad: "g", grupo: "Por porción" },
      { nombre: "Provenzal", cantidad: 10, unidad: "g", grupo: "Por porción" },
      { nombre: "Alioli", cantidad: 30, unidad: "g", grupo: "Por porción" },
      { nombre: "Morcilla", cantidad: 100, unidad: "g", grupo: "Por porción" },
      { nombre: "Limón (1 cuña)", cantidad: 20, unidad: "g", grupo: "Por porción" },
      { nombre: "Ciboulette", cantidad: 10, unidad: "g", grupo: "Por porción" },
      { nombre: "Cebollas medianas", cantidad: 3, unidad: "u", grupo: "Grupo A" },
      { nombre: "Arroz carnaroli", cantidad: 3, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Vino blanco", cantidad: 500, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 3, unidad: "l", grupo: "Grupo B" },
      { nombre: "Sal marina", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Cortar la cebolla en brunoise bien prolija.",
      "Calentar en una olla los 3 litros de agua hasta hervor. Llevar dos o tres bandejas planas de horno al freezer para que estén bien frías.",
      "Calentar el aceite en una olla a fuego bajo y agregar las cebollas en brunoise. Sofreír solo hasta que estén transparentes. No tienen que tomar color.",
      "Agregar el arroz y nacarar un minuto.",
      "Subir el fuego al máximo y agregar el vino blanco. Debe evaporar y reducir bien rápido.",
      "Cuando esté casi seco, agregar el agua de una sola vez y una pizca de sal.",
      "Cocinar a fuego medio/fuerte con cuidado de que no se pegue. No hay que estar revolviendo todo el tiempo porque el arroz larga almidón (no es lo que queremos) pero sí de vez en cuando para despegar y que se cocine parejo.",
      "Cuando casi no quede líquido sacar del fuego y pasar rápidamente a las placas previamente enfriadas. Estirar en una capa bien fina y hacer cortes en cuadrícula con una espátula. Llevar al freezer inmediatamente y dejar enfriar unos 10 minutos. Después se puede llevar a cámara o heladera.",
      "Porcionar en bolsas de 200 g para el servicio.",
    ],
    rendimiento: "33 porciones",
  },
  {
    id: "23",
    nombre: "Vinagreta de Curry",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Aceite de girasol", cantidad: 300, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Garam masala", cantidad: 250, unidad: "g", grupo: "Grupo A" },
      { nombre: "Aceto balsámico (reducción)", cantidad: 200, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 40, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 300, unidad: "ml", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Infusionar el garam masala en el aceite de girasol a fuego mínimo durante unos minutos. Colar.",
      "Dejar enfriar hasta temperatura ambiente y después emulsionar en licuadora el aceite infusionado, el aceite de oliva y los vinagres.",
      "Poner en biberón y reservar para el servicio.",
    ],
  },
  {
    id: "24",
    nombre: "Garam Masala",
    categoria: "Condimentos",
    ingredientes: [
      { nombre: "Coriandro", cantidad: 0.5, unidad: "taza" },
      { nombre: "Semillas de comino", cantidad: 0.25, unidad: "taza" },
      { nombre: "Canela", cantidad: 4, unidad: "ramas" },
      { nombre: "Laurel", cantidad: 4, unidad: "hojas" },
      { nombre: "Cardamomo (abierto con la vaina)", cantidad: 8, unidad: "u" },
      { nombre: "Clavo de olor", cantidad: 15, unidad: "u" },
      { nombre: "Anís estrellado", cantidad: 2, unidad: "u" },
      { nombre: "Pimienta de Sichuan", cantidad: 1, unidad: "cta" },
      { nombre: "Nuez moscada", cantidad: 1, unidad: "u" },
      { nombre: "Pimienta negra", cantidad: 20, unidad: "granos" },
      { nombre: "Hinojo", cantidad: 1, unidad: "cda" },
      { nombre: "Fenogreco", cantidad: 0.5, unidad: "cda" },
    ],
    instrucciones: [
      "Tostar todo junto a horno bajo y reducir a polvo en licuadora o procesadora. Reservar en tupper.",
    ],
    notas: "Se usa en la Vinagreta de Curry.",
  },
  {
    id: "25",
    nombre: "Fumet de Pescado",
    categoria: "Fondos",
    ingredientes: [
      { nombre: "Espinas y cabezas de pescado blanco (sin branquias)", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Cebolla", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Apio", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Puerro", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Zanahoria", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Laurel", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Perejil", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Agua fría", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Lavar muy bien el Grupo A.",
      "Rehogar el Grupo B sin que tomen color.",
      "Agregar las espinas, cabezas y agua.",
      "Llevar a hervor suave y espumar.",
      "Agregar perejil y laurel.",
      "Cocinar de 20 a 25 minutos.",
      "Colar por chino fino y enfriar.",
    ],
  },
  {
    id: "26",
    nombre: "Manteca de Ajo",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Manteca", cantidad: 400, unidad: "g" },
      { nombre: "Ajo", cantidad: 25, unidad: "g" },
    ],
    instrucciones: [
      "Emulsionar en thermomix.",
      "Derretir para usar en el servicio, pintando los langostinos durante la cocción.",
    ],
  },
  {
    id: "27",
    nombre: "Sofrito de Azafrán",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Cebolla", cantidad: 2.5, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Zanahoria", cantidad: 2, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Morrón verde", cantidad: 4, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Verdeo entero", cantidad: 700, unidad: "g", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Tomate triturado", cantidad: 2, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Caldo de pollo", cantidad: 2, unidad: "l", grupo: "Grupo C" },
      { nombre: "Azafrán", cantidad: 2, unidad: "g", grupo: "Grupo C" },
      { nombre: "Cabezas de ajo asado", cantidad: 12, unidad: "u", grupo: "Grupo D" },
    ],
    instrucciones: [
      "Cortar el Grupo A en brunoise y poner a sofreír a fuego medio hasta bien cocido casi pasta.",
      "Agregar el tomate triturado y cocinar hasta casi seco.",
      "Ir mojando con el caldo de pollo y azafrán como si fuera un risotto.",
      "Cuando haya absorbido todo el caldo, agregar la pulpa de las cabezas de ajo asado. Apagar el fuego. Enfriar, envasar al vacío y congelar.",
    ],
    notas: "La ficha tiene anotaciones manuscritas: en el Grupo C figura 'caldo de langostinos c/n' y en el Grupo D el coral de langostinos aparece tachado ('ver cantidad').",
  },
  {
    id: "28",
    nombre: "Caldo de Pollo Dorado",
    categoria: "Fondos",
    ingredientes: [
      { nombre: "Huesos de pollo dorados", cantidad: 3, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Alitas de pollo doradas", cantidad: 1, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Cebolla en juliana", cantidad: 300, unidad: "g", grupo: "Grupo B" },
      { nombre: "Zanahorias en mirepoix", cantidad: 450, unidad: "g", grupo: "Grupo B" },
      { nombre: "Apio en mirepoix (ramas)", cantidad: 190, unidad: "g", grupo: "Grupo B" },
      { nombre: "Puerro en mirepoix", cantidad: 50, unidad: "g", grupo: "Grupo B" },
      { nombre: "Aceite neutro", cantidad: 10, unidad: "ml", grupo: "Grupo C" },
      { nombre: "Agua fría", cantidad: 10, unidad: "l", grupo: "Grupo C" },
      { nombre: "Laurel", cantidad: 2, unidad: "hojas", grupo: "Grupo D" },
      { nombre: "Tomillo", cantidad: 10, unidad: "ramitas", grupo: "Grupo D" },
      { nombre: "Romero", cantidad: 5, unidad: "g", grupo: "Grupo D" },
      { nombre: "Perejil", cantidad: 7, unidad: "g", grupo: "Grupo D" },
      { nombre: "Pimienta", cantidad: 7, unidad: "g", grupo: "Grupo D" },
    ],
    instrucciones: [
      "Dorar las carcasas por un lado y las alitas por el otro. Horno a 190 °C por 40 minutos aproximadamente.",
      "En una olla alta (la de la pasta) sofreír la cebolla hasta que empiece a dorar. Después agregar la zanahoria, apio, puerro y dejar que tome un poco de color.",
      "Una vez dorado, agregar las carcasas, alitas y aromáticas (menos el perejil). Agregar el agua. Una vez que rompe hervor bajar el fuego a mínimo y cocinar de 2 a 3 horas.",
      "Antes de apagar, agregar el perejil y dejar un rato para que termine de infusionarse.",
      "Filtrar, enfriar y envasar al vacío.",
    ],
  },
  {
    id: "29",
    nombre: "Manzanas Prensadas",
    categoria: "Guarniciones",
    ingredientes: [
      { nombre: "Azúcar", cantidad: 200, unidad: "g", grupo: "Almíbar" },
      { nombre: "Agua", cantidad: 400, unidad: "ml", grupo: "Almíbar" },
      { nombre: "Sal", cantidad: 1, unidad: "cdta", grupo: "Almíbar" },
      { nombre: "Cáscaras de las 4 manzanas", cantidad: 0, unidad: "c/n", grupo: "Almíbar" },
      { nombre: "Hojas tiernas de apio", cantidad: 10, unidad: "g", grupo: "Almíbar" },
      { nombre: "Manzanas", cantidad: 4, unidad: "u", grupo: "Manzanas" },
      { nombre: "Almíbar (filtrado)", cantidad: 260, unidad: "ml", grupo: "Manzanas" },
    ],
    instrucciones: [
      "Almíbar: llevar todo junto hasta que rompa el hervor y apagar. Solo debe hervir; si reduce, está mal.",
      "Pelar y cortar las manzanas en cubos de 1cm x 1cm.",
      "Poner en un cambro con 260 ml de almíbar o la cantidad necesaria para cubrir, ni más ni menos.",
      "Comprimir. Llevar el cambro abierto a la máquina de vacío seteada: temp vacuum high, Vacuum 30, Sealing 2.0.",
    ],
    notas: "El almíbar para las manzanas va filtrado. Las hojas de apio son las de adentro, blandas y amarillitas.",
  },
  {
    id: "30",
    nombre: "Bearnesa",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Manteca clarificada", cantidad: 500, unidad: "g", grupo: "Manteca de ají" },
      { nombre: "Ají molido", cantidad: 25, unidad: "g", grupo: "Manteca de ají" },
      { nombre: "Agua fría", cantidad: 500, unidad: "ml", grupo: "Gel de xantana" },
      { nombre: "Goma xántica", cantidad: 12, unidad: "g", grupo: "Gel de xantana" },
      { nombre: "Yemas", cantidad: 10, unidad: "u", grupo: "Bearnesa A" },
      { nombre: "Manteca de ají", cantidad: 380, unidad: "g", grupo: "Bearnesa A" },
      { nombre: "Perejil picado", cantidad: 15, unidad: "g", grupo: "Bearnesa B" },
      { nombre: "Orégano picado", cantidad: 10, unidad: "g", grupo: "Bearnesa B" },
      { nombre: "Vinagre de vino tinto", cantidad: 12, unidad: "ml", grupo: "Bearnesa B" },
      { nombre: "Ajo rallado", cantidad: 0.5, unidad: "u", grupo: "Bearnesa B" },
      { nombre: "Sal fina", cantidad: 0, unidad: "c/n", grupo: "Bearnesa B" },
      { nombre: "Gel de goma xántica", cantidad: 0.5, unidad: "g", grupo: "Bearnesa C" },
    ],
    instrucciones: [
      "Manteca de ají: clarificar la manteca. Cuando esté lista agregar el ají molido para infusionar. Volcar en un GN 1/1 y luego porcionar en bloques de 500 g.",
      "Gel de xantana: poner el agua fría en la licuadora, agregar la goma xántica de golpe y procesar hasta lograr una pasta. Conservar en heladera.",
      "Poner las yemas en thermomix y llevar a 65 grados durante 6 minutos. Cuando las yemas estén aireadas, emulsionar con la manteca de ají en forma de hilo.",
      "Agregar todo el grupo Bearnesa B y rectificar la sal si es necesario. Por último, agregar el gel. Reservar en servicio a temperatura ambiente.",
    ],
    notas: "La ficha corrige a mano la manteca de ají a 380 g.",
  },
  {
    id: "31",
    nombre: "Ali Oli de Huevo",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Huevos", cantidad: 6, unidad: "u", grupo: "Grupo A" },
      { nombre: "Yemas", cantidad: 3, unidad: "u", grupo: "Grupo A" },
      { nombre: "Ajo (medio diente)", cantidad: 6, unidad: "g", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 1350, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 220, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Jugo de limón", cantidad: 100, unidad: "ml", grupo: "Grupo C" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Procesar el Grupo A y emulsionar agregando el Grupo B en forma de hilo. Condimentar con el Grupo C.",
    ],
    notas: "La ficha solo trae ingredientes; el procedimiento sigue el patrón de la casa.",
  },
  {
    id: "32",
    nombre: "Pollo Frito",
    categoria: "Elaboraciones",
    ingredientes: [
      { nombre: "Agua fría", cantidad: 2, unidad: "l", grupo: "Brine A" },
      { nombre: "Sal fina", cantidad: 120, unidad: "g", grupo: "Brine A" },
      { nombre: "Laurel", cantidad: 4, unidad: "hojas", grupo: "Brine B" },
      { nombre: "Pimienta en grano", cantidad: 28, unidad: "g", grupo: "Brine B" },
      { nombre: "Semillas de comino", cantidad: 7, unidad: "g", grupo: "Brine B" },
      { nombre: "Ají molido", cantidad: 20, unidad: "g", grupo: "Brine B" },
      { nombre: "Ajo aplastado", cantidad: 60, unidad: "g", grupo: "Brine B" },
      { nombre: "Fenogreco", cantidad: 12, unidad: "g", grupo: "Brine B" },
      { nombre: "Coriandro", cantidad: 12, unidad: "g", grupo: "Brine B" },
      { nombre: "Piel de limón", cantidad: 0, unidad: "c/n", grupo: "Brine B" },
      { nombre: "Pechugas de pollo limpias", cantidad: 2.2, unidad: "kg", grupo: "Brine C" },
      { nombre: "Harina 0000", cantidad: 600, unidad: "g", grupo: "Mejunje A" },
      { nombre: "Pimienta blanca", cantidad: 15, unidad: "g", grupo: "Mejunje A" },
      { nombre: "Sal fina", cantidad: 16, unidad: "g", grupo: "Mejunje A" },
      { nombre: "Leche entera", cantidad: 700, unidad: "g", grupo: "Mejunje B" },
      { nombre: "Copos de maíz", cantidad: 250, unidad: "g", grupo: "Apanado A" },
      { nombre: "Harina 0000", cantidad: 250, unidad: "g", grupo: "Apanado B" },
      { nombre: "Sal", cantidad: 10, unidad: "g", grupo: "Apanado B" },
    ],
    instrucciones: [
      "Brine: en una olla, llevar el Brine A al fuego hasta disolver. Una vez disuelta la salmuera, agregar el Brine B y reservar hasta enfriar. Agregar las pechugas de pollo y dejar en la salmuera 24 horas.",
      "Mejunje: mezclar el Mejunje A en un bowl, luego integrar el Mejunje B con batidor de globo para que no queden grumos. Por otro lado cortar las pechugas de tamaño similar y dejar en el mejunje durante el servicio.",
      "Apanado: romper el Apanado A y mezclar con el Apanado B. Poner en un bowl y apanar a la minute en el servicio.",
    ],
  },
  {
    id: "33",
    nombre: "Ranch",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Queso crema", cantidad: 200, unidad: "g", grupo: "Grupo A" },
      { nombre: "Ali oli", cantidad: 400, unidad: "g", grupo: "Grupo B" },
      { nombre: "Cebolla en polvo", cantidad: 20, unidad: "g", grupo: "Grupo B" },
      { nombre: "Ciboulette picado", cantidad: 10, unidad: "g", grupo: "Grupo B" },
      { nombre: "Perejil picado", cantidad: 10, unidad: "g", grupo: "Grupo B" },
      { nombre: "Eneldo picado", cantidad: 10, unidad: "g", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Ralladura de limón", cantidad: 1, unidad: "u", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Ablandar el queso crema batiéndolo en la KitchenAid o a mano.",
      "Unir todo lo demás.",
    ],
  },
  {
    id: "35",
    nombre: "Crema Ácida",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Crema doble", cantidad: 250, unidad: "g" },
      { nombre: "Vinagre de alcohol", cantidad: 30, unidad: "g" },
    ],
    instrucciones: [
      "Mezclar todo directamente en el biberón y dejar reposar 2 horas.",
      "Batirlo dentro del biberón hasta que espese. Dura 2 días.",
    ],
  },
  {
    id: "36",
    nombre: "Emulsión de Remolacha",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Remolachas", cantidad: 1.5, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Azúcar", cantidad: 0.5, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Agua", cantidad: 0.5, unidad: "l", grupo: "Grupo A" },
      { nombre: "Vinagre blanco de alcohol", cantidad: 0.5, unidad: "l", grupo: "Grupo A" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Pelar y lavar las remolachas. Rallar a mano.",
      "Colocar en una olla las remolachas ralladas, el azúcar, el vinagre y el agua. Llevar a hervor y bajar el fuego. Cocinar hasta que la remolacha esté bien cocida.",
      "Filtrar el líquido y reservar.",
      "Poner la remolacha en un vaso de licuadora y procesar. Agregar sal. Si hace falta, agregar líquido de cocción para llevar a textura.",
      "Pasar por chino fino. Guardar en biberón para servicio.",
    ],
    rendimiento: "1,7 kg",
  },
  {
    id: "37",
    nombre: "Pesca Curada de Anafe",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Lisas de mar", cantidad: 30, unidad: "u", grupo: "Grupo A" },
      { nombre: "Sal fina", cantidad: 1920, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 16, unidad: "l", grupo: "Grupo B" },
      { nombre: "Vinagre de manzana", cantidad: 16, unidad: "l", grupo: "Grupo C" },
      { nombre: "Azúcar mascabo", cantidad: 32, unidad: "cda", grupo: "Grupo C" },
      { nombre: "Pimienta negra", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Pimienta de Jamaica", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Hoja de laurel", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Ají molido", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
      { nombre: "Aceite de girasol", cantidad: 2, unidad: "l", grupo: "Grupo D" },
    ],
    instrucciones: [
      "Limpiar la lisa retirando escamas y vísceras. Filetear y sacar las espinas de cada filet. Reservar el pescado y guardar las espinas y cabezas para otras preparaciones.",
      "Hacer una salmuera con el Grupo B y enfriar a 4 grados antes de usar.",
      "Sumergir los filetes de lisa en la salmuera y reservar tapado en heladera por 24 horas.",
      "Mientras tanto colocar en una olla todos los ingredientes del Grupo C y llevar a hervor. Enfriar y reservar.",
      "Una vez pasadas las 24 horas en salmuera retirar los filetes de lisa.",
      "Colocar los filetes en el vinagre especiado. Sellar al vacío y reservar en heladera 48 horas, mover los filetes cada 12 horas para que todos estén en contacto con el vinagre, por lo menos 24 horas.",
      "Sacar los filetes del vinagre y envasar al vacío con aceite de girasol.",
      "Sacar los filetes de la bolsa de vacío y escurrir bien. Secar con papel. Retirar la piel de los filetes y cortar en fetas bien finas.",
      "Porcionar en 80 g por plato.",
    ],
    notas: "Se puede reemplazar la lisa de mar por anchoa de banco.",
  },
  {
    id: "38",
    nombre: "Pickle de Remolacha",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Remolacha", cantidad: 2.25, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Azúcar", cantidad: 250, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 1.25, unidad: "l", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 50, unidad: "g", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 1, unidad: "l", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Pelar y lavar la remolacha.",
      "Cortar en cubos de 1 cm x 1 cm bien prolijos.",
      "Colocar en una olla todos los ingredientes del Grupo B y llevar a hervor. Bajar el fuego.",
      "Agregar los cubos de remolacha y cocinar a fuego bajo hasta que estén cocidos.",
      "Es importante ir probando durante la cocción. No buscamos que se pasen pero tampoco tienen que quedar duros. Hay que sacarlos cuando estén al dente y dejar enfriar en el líquido de cocción.",
    ],
    rendimiento: "1,75 kg aprox.",
  },
  {
    id: "39",
    nombre: "Aderezo Caesar",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Anchoas", cantidad: 3, unidad: "u", grupo: "Grupo A" },
      { nombre: "Ajo", cantidad: 1, unidad: "diente", grupo: "Grupo A" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Yema", cantidad: 1, unidad: "u", grupo: "Grupo A" },
      { nombre: "Huevo", cantidad: 1, unidad: "u", grupo: "Grupo A" },
      { nombre: "Reggianito rallado", cantidad: 60, unidad: "g", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 180, unidad: "g", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 20, unidad: "g", grupo: "Grupo B" },
      { nombre: "Jugo de limón", cantidad: 25, unidad: "g", grupo: "Grupo C" },
      { nombre: "Vinagre de alcohol", cantidad: 10, unidad: "g", grupo: "Grupo C" },
      { nombre: "Aceto balsámico", cantidad: 6, unidad: "g", grupo: "Grupo C" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Poner el Grupo A en la licuadora y licuar.",
      "Emulsionar con el Grupo B y condimentar con el Grupo C.",
    ],
  },
  {
    id: "40",
    nombre: "Pangrattato de Parmesano",
    categoria: "Condimentos",
    ingredientes: [
      { nombre: "Focaccia", cantidad: 300, unidad: "g" },
      { nombre: "Reggianito", cantidad: 150, unidad: "g" },
      { nombre: "Aceite de oliva", cantidad: 40, unidad: "ml" },
      { nombre: "Sal", cantidad: 5, unidad: "g" },
    ],
    instrucciones: [
      "Procesar todo junto en la Thermomix hasta lograr textura de arenado.",
      "Pasar a placa y llevar al horno a 150 °C, revolviendo cada 10 minutos hasta que esté dorado y crocante.",
    ],
  },
  {
    id: "41",
    nombre: "Gazpacho Blanco",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Almendras remojadas y peladas", cantidad: 250, unidad: "g", grupo: "Grupo A" },
      { nombre: "Pepino pelado", cantidad: 120, unidad: "g", grupo: "Grupo A" },
      { nombre: "Apio con hojas", cantidad: 50, unidad: "g", grupo: "Grupo A" },
      { nombre: "Ajo", cantidad: 1, unidad: "g", grupo: "Grupo A" },
      { nombre: "Cebolla blanca", cantidad: 70, unidad: "g", grupo: "Grupo A" },
      { nombre: "Agua", cantidad: 400, unidad: "ml", grupo: "Grupo A" },
      { nombre: "Aceite de girasol", cantidad: 150, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Aceite de oliva", cantidad: 50, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Vinagre de alcohol", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Licuar el Grupo A hasta que quede lo más liso posible.",
      "Emulsionar y condimentar con el Grupo B.",
      "Pasar por chino fino.",
    ],
    notas: "Dura 3 días.",
  },
  {
    id: "42",
    nombre: "Paté (Montaje)",
    categoria: "Elaboraciones",
    ingredientes: [
      { nombre: "Paté", cantidad: 20, unidad: "g" },
      { nombre: "Financier", cantidad: 20, unidad: "g" },
      { nombre: "Chutney de estación", cantidad: 6, unidad: "g" },
      { nombre: "Aceite de oliva", cantidad: 0, unidad: "c/n" },
      { nombre: "Sal en escamas", cantidad: 0, unidad: "c/n" },
      { nombre: "Perejil crespo o ciboulette", cantidad: 0, unidad: "c/n" },
    ],
    instrucciones: [
      "Montaje de servicio según ficha.",
    ],
    notas: "Especificación de montaje del plato, no una elaboración.",
  },
  {
    id: "43",
    nombre: "Chutney de Peras",
    categoria: "Conservas",
    ingredientes: [
      { nombre: "Peras", cantidad: 375, unidad: "g", grupo: "Grupo A" },
      { nombre: "Manzana verde pelada", cantidad: 60, unidad: "g", grupo: "Grupo A" },
      { nombre: "Tomate", cantidad: 125, unidad: "g", grupo: "Grupo A" },
      { nombre: "Cebolla blanca", cantidad: 60, unidad: "g", grupo: "Grupo A" },
      { nombre: "Pasas de uva negra", cantidad: 6, unidad: "g", grupo: "Grupo B" },
      { nombre: "Naranja (ralladura y jugo)", cantidad: 1, unidad: "u", grupo: "Grupo B" },
      { nombre: "Azúcar mascabo o rubia", cantidad: 150, unidad: "g", grupo: "Grupo B" },
      { nombre: "Ají molido", cantidad: 0.5, unidad: "cda", grupo: "Grupo B" },
      { nombre: "Nuez moscada", cantidad: 0.25, unidad: "cda", grupo: "Grupo B" },
      { nombre: "Jengibre fresco", cantidad: 15, unidad: "g", grupo: "Grupo B" },
      { nombre: "Vinagre de manzana", cantidad: 150, unidad: "g", grupo: "Grupo B" },
      { nombre: "Sal", cantidad: 0.5, unidad: "cda", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Cortar todo en mirepoix pequeña.",
      "Poner en olla a fuego medio y reducir hasta casi seco.",
      "Procesar en caliente, rectificar de sabor y tamizar.",
    ],
    rendimiento: "620 g de chutney",
    notas: "Se sustituye la pera por la fruta de estación (ejemplo: durazno, membrillo).",
  },
  {
    id: "44",
    nombre: "Reducción para Paté",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Oporto", cantidad: 1, unidad: "l" },
      { nombre: "Vino tinto", cantidad: 1, unidad: "l" },
      { nombre: "Cognac", cantidad: 1, unidad: "l" },
    ],
    instrucciones: [
      "Unir todo en una olla y reducir a fuego medio hasta casi punto glasa. Enfriar a temperatura ambiente.",
    ],
    notas: "Reducción de la ficha Paté de Anafe.",
  },
  {
    id: "45",
    nombre: "Ragú de Costilla",
    categoria: "Elaboraciones",
    ingredientes: [
      { nombre: "Costilla de cerdo deshuesada en cubos pequeños", cantidad: 3, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Cebolla brunoise", cantidad: 1, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Ajo brunoise", cantidad: 130, unidad: "g", grupo: "Grupo B" },
      { nombre: "Romero picado", cantidad: 3, unidad: "ramas", grupo: "Grupo B" },
      { nombre: "Pimentón", cantidad: 100, unidad: "g", grupo: "Grupo B" },
      { nombre: "Vino blanco", cantidad: 120, unidad: "ml", grupo: "Grupo C" },
      { nombre: "Cognac", cantidad: 100, unidad: "ml", grupo: "Grupo C" },
      { nombre: "Caldo de pollo / conejo", cantidad: 4, unidad: "l", grupo: "Grupo D" },
    ],
    instrucciones: [
      "Salpimentar la costilla y dorar en el disco por tandas y sin nada de aceite.",
      "Una vez dorada, pasar a otro recipiente y poner a rehogar la cebolla, el ajo y el romero picado. Una vez que empiece a tomar color, agregar el pimentón.",
      "Agregar la carne marcada y desglasar con el vino y el cognac; dejar evaporar el alcohol.",
      "Ir agregando el caldo de a poco hasta que la carne esté bien tierna, reponiendo el líquido a medida que se evapora.",
      "Enfriar y estirar en placa GN y congelar. Porcionar al día siguiente.",
    ],
  },
  {
    id: "46",
    nombre: "Everything Seasoning",
    categoria: "Condimentos",
    ingredientes: [
      { nombre: "Sésamo blanco", cantidad: 220, unidad: "g", grupo: "Como sal - A" },
      { nombre: "Sésamo negro", cantidad: 150, unidad: "g", grupo: "Como sal - A" },
      { nombre: "Sal en escamas", cantidad: 180, unidad: "g", grupo: "Como sal - B" },
      { nombre: "Amapola", cantidad: 100, unidad: "g", grupo: "Como sal - B" },
      { nombre: "Ajo seco granulado", cantidad: 170, unidad: "g", grupo: "Como sal - B" },
      { nombre: "Cebolla seca en escamas", cantidad: 180, unidad: "g", grupo: "Como sal - B" },
      { nombre: "Sésamo blanco", cantidad: 220, unidad: "g", grupo: "Para focaccia" },
      { nombre: "Sésamo negro", cantidad: 150, unidad: "g", grupo: "Para focaccia" },
      { nombre: "Sal en escamas", cantidad: 180, unidad: "g", grupo: "Para focaccia" },
      { nombre: "Amapola", cantidad: 100, unidad: "g", grupo: "Para focaccia" },
      { nombre: "Ajo seco granulado", cantidad: 170, unidad: "g", grupo: "Para focaccia" },
      { nombre: "Cebolla seca en escamas", cantidad: 180, unidad: "g", grupo: "Para focaccia" },
    ],
    instrucciones: [
      "Para usar como sal: tostar el Grupo A y unir con el Grupo B.",
      "Para usar en focaccia: unir todo.",
    ],
    rendimiento: "1 kg por preparación",
  },
  {
    id: "47",
    nombre: "Fondo Rojo de Pescado",
    categoria: "Fondos",
    ingredientes: [
      { nombre: "Espinas, cabezas y aletas de pescado blanco", cantidad: 3.1, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Carcasas y cabezas de langostinos", cantidad: 0, unidad: "c/n", grupo: "Grupo A" },
      { nombre: "Tomates", cantidad: 8, unidad: "u", grupo: "Grupo B" },
      { nombre: "Anís estrellado", cantidad: 2, unidad: "u", grupo: "Grupo B" },
      { nombre: "Semillas de hinojo", cantidad: 10, unidad: "u", grupo: "Grupo B" },
      { nombre: "Fumet blanco", cantidad: 0, unidad: "c/n", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Limpiar bien las cabezas de pescado removiendo ojos y agallas. Poner en agua con hielo las espinas, las cabezas y aletas un rato. Después escurrir y secar bien.",
      "Poner las cabezas y carcasas de langostino en agua con hielo un rato. Escurrir y secar bien.",
      "Cortar los tomates por la mitad y poner a fuego fuerte SIN ACEITE en una sartén por el lado plano. Queremos que se queme. Cuando esté listo sacar y reservar.",
      "En una olla de base ancha dorar a fuego medio con un poco de aceite de girasol las espinas y cabezas sin apilar. Dar vuelta cuando tengan un buen dorado y después retirar a un cambro.",
      "Levantar de nuevo la temperatura de la olla y agregar un poco de aceite si hace falta. Dorar a fuego fuerte las cabezas y carcasas de langostinos sin apilar. Si hace falta, dorarlos en tandas. Cuando estén doradas machacar fuerte para que suelten todo el coral.",
      "Agregar en la olla las espinas doradas, los tomates quemados, el anís y las semillas de hinojo.",
      "Mojar con fumet blanco apenas hasta cubrir y subir el fuego para que rompa el hervor.",
      "Cuando hierva, bajar el fuego y espumar. Cocinar durante 40 minutos.",
      "Cuando pase el tiempo volver a machacar para soltar el colágeno que queda en las espinas y colar por chino fino.",
      "Enfriar rápido en cámara.",
    ],
    notas: "El caldo que se usa para el arroz de calamar. Puede servir de base para salsas también. Si no hay fumet blanco, usar agua, pero para la próxima tener sí o sí porque cambia mucho el resultado.",
  },
  {
    id: "48",
    nombre: "Fondo Oscuro de Pollo (Demi Glace)",
    categoria: "Fondos",
    ingredientes: [
      { nombre: "Carcasa de pollo", cantidad: 6.5, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Alitas de pollo", cantidad: 3, unidad: "kg", grupo: "Grupo A" },
      { nombre: "Cebolla", cantidad: 1.7, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Zanahoria", cantidad: 1.7, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Tomates", cantidad: 1, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Apio", cantidad: 1, unidad: "kg", grupo: "Grupo B" },
      { nombre: "Bouquet garni", cantidad: 1, unidad: "u", grupo: "Grupo B" },
      { nombre: "Hongos secos", cantidad: 100, unidad: "g", grupo: "Grupo B" },
      { nombre: "Aceite de girasol", cantidad: 0, unidad: "c/n", grupo: "Grupo B" },
      { nombre: "Manitas de cerdo", cantidad: 5, unidad: "kg", grupo: "Grupo C" },
      { nombre: "Vino tinto", cantidad: 0.5, unidad: "l", grupo: "Grupo D" },
      { nombre: "Agua", cantidad: 20, unidad: "l", grupo: "Grupo E" },
    ],
    instrucciones: [
      "Precalentar el horno a 180 grados.",
      "Poner las carcasas y las alitas en bandejas y asar a 180 hasta que estén bien doradas. Dar vuelta a mitad de cocción para que el dorado sea parejo. Buscamos caramelización de todos lados. Una sola carcasa o alita quemada puede arruinar una tirada entera de fondo (el sabor amargo de los huesos quemados es muy fuerte y, aunque parezca poco, lo arruina todo).",
      "Poner las manitas de cerdo en una olla con agua fría y llevar a hervor. Apenas hierve apagar el fuego y escurrir. El agua no se usa.",
      "Hacer una mirepoix de cebolla, zanahoria y apio. Cortar los tomates en pedazos medianos. Armar un bouquet garni con dos hojas de laurel, dos ramas de romero y un poco de perejil. Envolver en una hoja verde de puerro o directamente con un hilo para poder sacar después.",
      "En una olla grande de fondo ancho dorar a fuego medio/bajo la mirepoix de cebolla, zanahoria y apio. Mover cada tanto para que no se queme y la cocción sea pareja. Buscamos un dorado intenso como el de las carcasas.",
      "Cuando la mirepoix ya esté dorada agregar los tomates y mover bien para que levanten un poco la caramelización del fondo.",
      "Cuando los tomates hayan evaporado todo el agua agregar el vino tinto y rascar bien el fondo de la olla para terminar de levantar todo. Reducir el vino y agregar el bouquet garni, los hongos secos, las carcasas, las alitas y las manitas de cerdo. Agregar los 20 litros de agua y llevar a fuego fuerte hasta hervor.",
      "Desglasar las fuentes del horno de las carcasas y las alitas si hace falta para levantar toda esa caramelización y agregar al fondo. Se puede usar un poco del vino de la receta o agua. Lo importante es no perder ese sabor del fondo de la bandeja. Si está quemado NO VA.",
      "Una vez que rompa el hervor bajar el fuego al mínimo y cocinar entre 6 y 8 horas espumando la superficie cuando sea necesario. NUNCA tiene que hervir fuerte. La burbuja tiene que ser suave y constante.",
      "Pasadas las 8 horas colar por chino y después por fino para que no quede ningún sólido. Enfriar en cámara por lo menos 12 horas, idealmente 24 horas. NUNCA poner el cambro o la olla directamente en el piso de la cámara: poner aros o algo para que no esté en contacto con el piso.",
      "Al día siguiente, retirar la grasa que queda en la superficie del fondo y poner el caldo en olla ancha a fuego medio/bajo. Reducir hasta obtener entre 4 y 5 litros de salsa. Ligar si hace falta para el servicio. NUNCA tiene que hervir fuerte: es una salsa que necesita tiempo, si se apura sale mal. Burbuja fina, suave y constante.",
      "Cuando está en su punto reservar en un cambro con film a piel (si no, se le forma una capa fea como a la salsa blanca) y tapa.",
    ],
    rendimiento: "4,5 litros",
    notas: "Es una salsa fácil de hacer pero que lleva mucho tiempo: mínimo dos días y ocupa espacio en cámara por lo menos una noche. Los huesos y las verduras tienen que estar muy bien dorados (no quemados) y la reducción del vino es importante para el sabor final. Las manitas de cerdo y las alitas suman colágeno para una textura sedosa; los hongos secos y las aromáticas suman profundidad de sabor.",
  },
  {
    id: "49",
    nombre: "Bechamel de Cheddar y Azul",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Manteca", cantidad: 90, unidad: "g", grupo: "Grupo A" },
      { nombre: "Harina 0000", cantidad: 90, unidad: "g", grupo: "Grupo A" },
      { nombre: "Leche entera", cantidad: 750, unidad: "ml", grupo: "Grupo B" },
      { nombre: "Reggianito rallado", cantidad: 160, unidad: "g", grupo: "Grupo C" },
      { nombre: "Queso azul", cantidad: 50, unidad: "g", grupo: "Grupo C" },
      { nombre: "Nuez moscada", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
      { nombre: "Tartufato", cantidad: 1, unidad: "cdta", grupo: "Grupo C" },
      { nombre: "Ajo rallado crudo", cantidad: 0.5, unidad: "dientes", grupo: "Grupo C" },
      { nombre: "Sal", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
      { nombre: "Pimienta blanca", cantidad: 0, unidad: "a gusto", grupo: "Grupo C" },
    ],
    instrucciones: [
      "Hacer un roux dorado con el Grupo A (un poquitín más que blanco, mucho menos que oscuro).",
      "Fuera del fuego ir agregando la leche de a poco, para evitar grumos. Una vez incorporada volver a fuego medio a cocinar por 3 minutos.",
      "Agregar los quesos y condimentar, batiendo hasta que se derritan los quesos. Probar, que esté rico.",
      "Llevar a kitchen aid y enfriar con lira a velocidad baja para no romper el ligue. Guardar en al menos 2 mangas.",
    ],
    notas: "Tartufato: solo si hay.",
  },
  {
    id: "50",
    nombre: "Masa de Pasta",
    categoria: "Masas",
    ingredientes: [
      { nombre: "Harina 0000", cantidad: 3000, unidad: "g", grupo: "Grupo A" },
      { nombre: "Yemas egg höns", cantidad: 900, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 600, unidad: "ml", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Disponer la harina (A) en la planetaria. En un bowl aparte, batir las yemas con el agua hasta romperlas.",
      "Hacer una corona con la harina y agregar el Grupo B. Integrar con el gancho hasta que la masa tome cuerpo.",
      "Retirar de la planetaria, llevar a la mesada y dividir en dos. Amasar cada bollo hasta obtener una superficie lisa y uniforme.",
      "Porcionar: spaghetti 110 g | garganelli, sopresinni, barchette 120 g.",
    ],
    rendimiento: "4,2 kg de masa",
  },
  {
    id: "51",
    nombre: "BBQ Coreana",
    categoria: "Salsas",
    ingredientes: [
      { nombre: "Salsa de soja light", cantidad: 440, unidad: "g", grupo: "Grupo A" },
      { nombre: "Agua", cantidad: 440, unidad: "g", grupo: "Grupo A" },
      { nombre: "Azúcar rubia", cantidad: 292, unidad: "g", grupo: "Grupo A" },
      { nombre: "Vinagre de arroz", cantidad: 84, unidad: "g", grupo: "Grupo A" },
      { nombre: "Chipotles", cantidad: 80, unidad: "g", grupo: "Grupo A" },
      { nombre: "Pimienta blanca", cantidad: 10, unidad: "g", grupo: "Grupo A" },
      { nombre: "Ajo rallado", cantidad: 8, unidad: "dientes", grupo: "Grupo A" },
      { nombre: "Jengibre rallado", cantidad: 60, unidad: "g", grupo: "Grupo A" },
      { nombre: "Maizena", cantidad: 30, unidad: "g", grupo: "Grupo B" },
      { nombre: "Agua", cantidad: 30, unidad: "g", grupo: "Grupo B" },
    ],
    instrucciones: [
      "Poner el Grupo A en olla y cocinar a fuego bajo hasta que se disuelva el azúcar.",
      "Retirar del fuego, licuar y tamizar.",
      "Disolver la maizena con el agua (Grupo B) y agregar a la preparación. Volver a llevar a hervor.",
    ],
  },
]

// Configuraciones de horno
export const configuracionesHorno: ConfiguracionHorno[] = [
  // Ejemplo:
  // {
  //   id: "1",
  //   titulo: "Croissants",
  //   descripcion: "Configuración óptima para croissants",
  //   temperatura: "200°C",
  //   tiempo: "18-20 min"
  // }
]

// Notas generales y tips
export const notasGenerales: NotaGeneral[] = [
  // Ejemplo:
  // {
  //   id: "1",
  //   titulo: "Conversión de levadura",
  //   contenido: "Levadura fresca a seca: dividir entre 3",
  //   categoria: "Conversiones"
  // }
]

// Categorías de recetas disponibles
export const categoriasRecetas = [
  "Masas",
  "Purés",
  "Salsas",
  "Conservas",
  "Fondos",
  "Elaboraciones",
  "Guarniciones",
  "Condimentos"
]

// Categorías de notas
export const categoriasNotas = [
  "Conversiones",
  "Tips",
  "Técnicas",
  "Temperaturas",
  "Otros"
]
